default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: microverse
  password: password
  timeout: 5000

development:
  <<: *default
  database: flight-book_development

test:
  <<: *default
  database: flight-book_test

production:
  <<: *default
  database: flight-book_production
  username: flight-book
  password: <%= ENV['FLIGHT-BOOK_DATABASE_PASSWORD'] %>
